---
title: "Spatial point pattern analysis"
author: "Genevieve Chiong"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sf)
library(spatstat)
library(maptools) 
library(sp)
library(raster)
library(tmap)
```

```{r}
# Read in the tree vole data 

voles <- read_sf(dsn = here("redtreevoledata"),
                 layer = "ds033") %>% 
  dplyr::select(COUNTY) %>% # only select the county attribute 
  filter(COUNTY == "HUM") %>% # only keep observations in Humboldt County
  st_transform(crs = 4326) # update CRS 

# Plot it (exploratory)
plot(voles)
```

```{r}
# Get Humboldt County outline
humboldt <- read_sf(dsn = here("redtreevoledata"),
                               layer = "california_county_shape_file") %>% 
  filter(NAME == "Humboldt") %>% # Isolate Humboldt County
  dplyr::select(NAME)  # Only keep one attribute (name) to simplify

# Set CRS
st_crs(humboldt) <- 4326 # Set CRS to match

# Plot them together
ggplot() + 
  geom_sf(data = humboldt,
          color = "darkorchid",
          fill = "darkorchid4",
          size = 1) +
  geom_sf(data = voles,
          color = "orange", 
          alpha = 0.7, 
          size = 2) +
  theme_minimal()
```

```{r}
voles_sp <- as(voles,"Spatial") # Convert to object 'Spatial'
proj4string(voles_sp) <- "+proj=utm +zone=10 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0" # Add UTM projection so that it's 2D (otherwise point pattern analysis invalid)

voles_ppp <- as(voles_sp, "ppp") # Convert to spatial point pattern

humboldt_sp <- as(humboldt, "Spatial") # Convert to object 'Spatial'
proj4string(humboldt_sp) <- "+proj=utm +zone=10 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0" # Add UTM projection

humboldt_win <- as(humboldt_sp, "owin") # Convert to spatial point pattern

# Combine as a point pattern object (points + window):
voles_full <- ppp(voles_ppp$x, voles_ppp$y, window = humboldt_win)

plot(voles_full) # Illegal point (outside window) shows up as the plus sign
```


## Make a kernel density plot:

### Density
```{r}
voles_density <- density(voles_full, sigma = 0.03)

plot(voles_density)
```


```{r}
# Can you start viewing this in tmap? Yes, rasterize it: 
wgs84 = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
vole_raster <- raster(voles_density, crs = wgs84)

# Then plot:
tmap_mode("view")

tm_shape(vole_raster) + 
  tm_raster(midpoint = NA,
            palette = "Reds",
            legend.show = FALSE)
```


## Nearest neighbor (G-function)

```{r}
r <- seq(0, 0.15, by = 0.005) # Make a sequence of distances over which you'll calculate G(r)

gfunction <- envelope(voles_full, fun = Gest, r = r, nsim = 100, nrank = 2) # calculate the actual and theoretical G(r) values, using 100 simulations of CRS for the "theoretical" outcome 

gfunction # Check the output of gfunction, then ... 

# Gather this to plot series in ggplot: 
gfunction_long <- gfunction %>% 
  as.data.frame() %>% 
  pivot_longer(cols = obs:hi, names_to = "model", values_to = "g_val")

# Then make a graph in ggplot: 
ggplot(data = gfunction_long, aes(x = r, 
                                  y = g_val, 
                                  group = model)) +
  geom_line(aes(color = model))
```


```{r}
# L-function: calculates the density of events within growing circles around each point 

r2 <- seq(0, 0.5, by = 0.05)

lfunction <- envelope(voles_full, fun = Lest, r = r2, nsim = 10, rank = 2, global = TRUE)

# Gather this to plot series in ggplot: 

lfunction_long <- lfunction %>% 
  as.data.frame() %>% 
  pivot_longer(col = obs:hi, names_to = "model", values_to = "k_val") 

ggplot(data = lfunction_long,
       aes(x = r,
           y = k_val,
           group = model)) +
  geom_line(aes(color = model))
```













